project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "**/*.qmd"
    - "!**/assets/**"

website:
  title: "Doing Data Analysis with AI"
  description: "A short course by Gábor Békés"
  site-url: "https://gabors-data-analysis.com/ai-course"
  
  navbar:
    title: "DA with AI"
    left:
      - href: index.qmd
        text: Home
      - href: weeks.qmd
        text: Weekly Content
      - href: assignments.qmd
        text: Assignments
      - href: resources.qmd
        text: Resources

  sidebar:
    style: "docked"
    contents:
      - section: "Course Weeks"
        contents:
          - text: "Week 0: AI-Assisted Coding Prep"
            href: week00/index.qmd
          - text: "Week 1: LLM Review"
            href: week01/index.qmd
          - text: "Week 2: Discovery and Documentation"  
            href: week02/index.qmd
          - text: "Week 3: Reporting Your Data Analysis"
            href: week03/index.qmd
          - text: "Week 4: Agentic AI with CLIs"
            href: week04/index.qmd
          - text: "Week 5: Using Text as Data"
            href: week05/index.qmd
          - text: "Week 6: Sentiment Analysis with AI"
            href: week06/index.qmd
          - text: "Week 7: Data Collect"
            href: week07/index.qmd
          - text: "Week 8: SQL with AI"
            href: week08/index.qmd
          - text: "Week 9: AI Research - Designing Z"
            href: week09/index.qmd
          - text: "Week 10: AI Research - Instrumental Variables"
            href: week10/index.qmd
          - text: "Week 11: AI Research - Difference in Differences"
            href: week11/index.qmd
          - text: "Week 12: Creating Dashboards and Online Apps"
            href: week12/index.qmd
          
      - section: "Case Studies"
        contents:
          - text: "World Values Survey"
            href: case-studies/VWS/index.qmd
          - text: "Austrian Hotels"
            href: case-studies/austria-hotels/index.qmd
          - text: "Football Interviews"
            href: case-studies/interviews/index.qmd
          - text: "US Earnings (CPS)"
            href: case-studies/earnings/index.qmd
          - text: "Employee Commits"
            href: case-studies/employee_commits/index.qmd
          - text: "Common Support (R)"
            href: case-studies/common-support-r/index.qmd

      - section: "Resources"
        contents:
          - text: "Glossary of LLM terms"
            href: da-knowledge/technical-terms-page.qmd
          - text: "Learn More"
            href: da-knowledge/beyond.qmd
          - text: "Which AI"
            href: da-knowledge/which-ai.qmd


      - section: "Slideshows"
        contents:
          - text: "Key concepts"
            href: https://gabors-data-analysis.com/courses/da-w-ai-2025/da-w-ai-01-llm-course.html
          - text: "Prompting, Context"
            href: https://gabors-data-analysis.com/courses/da-w-ai-2025/da-w-ai-02-prompting.html


format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    code-fold: false
    code-tools: true