project:
  type: website
  output-dir: _site

website:
  title: "Doing Data Analysis with AI"
  description: "A short course by Gábor Békés"
  site-url: "https://gabors-data-analysis.com/ai-course"
  
  navbar:
    title: "DA with AI"
    left:
      - href: index.qmd
        text: Home
      - href: weeks.qmd
        text: Weekly Content
      - href: assignments.qmd
        text: Assignments
      - href: resources.qmd
        text: Resources

  sidebar:
    style: "docked"
    contents:
      - section: "Course Weeks"
        contents:
          - text: "Week 0: Coding with AI"
            href: week00/index.qmd
          - text: "Week 1: LLM Review"
            href: week01/index.qmd
          - text: "Week 2: Documentation"  
            href: week02/index.qmd
          - text: "Week 3: Reports"
            href: week03/index.qmd
          - text: "Week 4: Join Tables"
            href: week04/index.qmd
          - text: "Week 5: Text as Data I"
            href: week05/index.qmd
          - text: "Week 6: Text as Data II"
            href: week06/index.qmd
          - text: "Week 7: Data Collect"
            href: week06/index.qmd
          - text: "Week 8: SQL with AI"
            href: week06/index.qmd
          - text: "Week 9: AI Research: Controls"
            href: week09/index.qmd
          - text: "Week 10: AI Research: IV"
            href: week10/index.qmd
          - text: "Week 11: AI Research: DiD"
            href: week11/index.qmd
          - text: "Week 12: Dashboards & Apps"
            href: week12/index.qmd
          
      - section: "Resources"
        contents:
          - text: "Learn More"
            href: learn-more/beyond.qmd
          - text: "Data"
            href: data/index.qmd
          - text: "Code"
            href: code/index.qmd
          - text: "Which AI"
            href: week01/assets/which-ai.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    code-fold: false
    code-tools: true